# ------------------------------------------------------------------------
#
# Copyright WSO2, Inc. (http://wso2.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License
#
# ------------------------------------------------------------------------
FROM docker.wso2.com/wso2am:2.1.0

COPY apim/carbon/ /mnt/wso2-artifacts

COPY apim/libs/mysql-connector-java-5.1.34-bin.jar /mnt/wso2-artifacts/repository/components/lib/
